from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
import json
import math
import time
from typing import Callable, Any

from shapely.geometry import Polygon, LineString, Point
from shapely.geometry.base import BaseGeometry
from shapely.validation import make_valid

from .chunks import ChunkExportEntry, chunk_summary, write_chunk_manifest, write_chunk_zip
from .dem import AUTO_ELEVATION_ATTRIBUTION, TERRAIN_TILE_ATTRIBUTION, make_terrain
from .export_3mf import write_3mf, validate_3mf
from .export_glb import write_glb
from .export_stl import write_stl
from .geo import make_local_projection, make_scaler
from .mesh_ops import (
    terrain_to_mesh,
    build_building_meshes,
    build_surface_layer_meshes,
    water_cutout_polygons_mm,
)
from .mesh_repair import repair_mesh_parts
from .mesh_types import MeshPart
from .osm import fetch_osm_json, fetch_osm_json_tiled, parse_osm_features, save_osm_json, OSMFeature
from .params import ModelParams, safe_output_stem
from .printability import printability_report

Progress = Callable[[str, float], None]


def _progress(progress: Progress | None, message: str, value: float) -> None:
    if progress:
        progress(message, value)


def attribution_text(params: ModelParams, terrain_source: str) -> str:
    lines = [
        "Generated by TopoTile Studio.",
        "",
        "Map vector data: Data © OpenStreetMap contributors, available under the Open Database License.",
        "OpenStreetMap: https://www.openstreetmap.org/copyright",
    ]
    if terrain_source == "uploaded_dem":
        lines.append("")
        if params.dem_attribution.strip():
            lines.append(f"Elevation data: {params.dem_attribution.strip()}")
        else:
            lines.append("Elevation data: user-supplied DEM GeoTIFF. Please add the DEM source attribution before publishing.")
    elif terrain_source == "auto_elevation":
        lines.append("")
        lines.append(AUTO_ELEVATION_ATTRIBUTION)
    elif terrain_source == "terrain_tiles":
        lines.append("")
        lines.append(TERRAIN_TILE_ATTRIBUTION)
    lines.append("")
    lines.append("This file is generated for local modeling and 3D printing workflows.")
    return "\n".join(lines)


def footprint_polygon_m(params: ModelParams, width_m: float, height_m: float) -> Polygon | None:
    if params.selection_shape == "rectangle":
        return None
    cx = width_m / 2.0
    cy = height_m / 2.0
    if params.selection_shape == "circle":
        radius = min(width_m, height_m) / 2.0
        if radius <= 0:
            return None
        return Point(cx, cy).buffer(radius, quad_segs=96)
    if params.selection_shape == "hexagon":
        radius = min(height_m / 2.0, width_m / math.sqrt(3.0))
        if radius <= 0:
            return None
        coords = [
            (cx + math.cos(-math.pi / 2.0 + i * math.pi / 3.0) * radius,
             cy + math.sin(-math.pi / 2.0 + i * math.pi / 3.0) * radius)
            for i in range(6)
        ]
        return Polygon(coords)
    return None


def rectangle_polygon_m(width_m: float, height_m: float) -> Polygon:
    return Polygon([(0.0, 0.0), (width_m, 0.0), (width_m, height_m), (0.0, height_m), (0.0, 0.0)])


def footprint_polygon_mm(footprint_m: Polygon | None, scaler) -> Polygon | None:
    if footprint_m is None or footprint_m.is_empty:
        return None
    exterior = [scaler.xy_to_mm(float(x), float(y)) for x, y in footprint_m.exterior.coords]
    holes = [[scaler.xy_to_mm(float(x), float(y)) for x, y in ring.coords] for ring in footprint_m.interiors]
    return Polygon(exterior, holes)


def clip_features_to_footprint(features: list[OSMFeature], footprint_m: BaseGeometry | None) -> list[OSMFeature]:
    if footprint_m is None or footprint_m.is_empty:
        return features
    clipped: list[OSMFeature] = []
    for feature in features:
        try:
            geom = feature.geometry_m.intersection(footprint_m)
        except Exception:
            continue
        if geom.is_empty:
            continue
        if not geom.is_valid:
            geom = make_valid(geom)
        if geom.is_empty:
            continue
        clipped.append(OSMFeature(layer=feature.layer, geometry_m=geom, tags=feature.tags, osm_id=feature.osm_id))
    return clipped


def chunk_bboxes(params: ModelParams) -> list[tuple[int, int, tuple[float, float, float, float]]]:
    lat_step = (params.north - params.south) / params.chunk_rows
    lon_step = (params.east - params.west) / params.chunk_cols
    chunks: list[tuple[int, int, tuple[float, float, float, float]]] = []
    for row in range(params.chunk_rows):
        south = params.south + row * lat_step
        north = params.north if row == params.chunk_rows - 1 else params.south + (row + 1) * lat_step
        for col in range(params.chunk_cols):
            west = params.west + col * lon_step
            east = params.east if col == params.chunk_cols - 1 else params.west + (col + 1) * lon_step
            chunks.append((row + 1, col + 1, (south, west, north, east)))
    return chunks


def export_chunk_models(
    params: ModelParams,
    output_dir: Path,
    dem_path: str | Path | None,
    osm_json: dict[str, Any],
    full_scale_mm_per_m: float,
) -> dict[str, Any] | None:
    if not params.chunk_export or params.chunk_rows * params.chunk_cols <= 1:
        return None

    chunk_root = output_dir / "chunks"
    chunk_root.mkdir(parents=True, exist_ok=True)
    entries: list[ChunkExportEntry] = []
    base_name = safe_output_stem(params.output_name)

    for row, col, bbox in chunk_bboxes(params):
        south, west, north, east = bbox
        chunk_projection = make_local_projection(south, west, north, east)
        chunk_max_size_mm = max(chunk_projection.width_m, chunk_projection.height_m) * full_scale_mm_per_m
        chunk_data = asdict(params)
        chunk_data.update({
            "south": south,
            "west": west,
            "north": north,
            "east": east,
            "max_size_mm": chunk_max_size_mm,
            "chunk_export": False,
            "project_name": f"{params.project_name} r{row:02d} c{col:02d}",
            "output_name": f"{base_name}_r{row:02d}_c{col:02d}",
        })
        chunk_params = ModelParams.from_dict(chunk_data)
        chunk_dir = chunk_root / f"r{row:02d}_c{col:02d}"
        summary = generate_model(
            chunk_params,
            chunk_dir,
            dem_path=dem_path,
            osm_json_override=osm_json,
            progress=None,
        )
        filename = str(summary["files"]["3mf"])
        src = chunk_dir / filename
        entries.append(ChunkExportEntry(
            row=row,
            col=col,
            filename=filename,
            path=src,
            bbox=bbox,
            model_width_mm=float(summary["model_width_mm"]),
            model_height_mm=float(summary["model_height_mm"]),
        ))

    manifest_path = write_chunk_manifest(output_dir, base_name, params.chunk_rows, params.chunk_cols, entries)
    zip_path = write_chunk_zip(output_dir, base_name, entries, manifest_path)
    return chunk_summary(params.chunk_rows, params.chunk_cols, entries, zip_path, manifest_path)


def generate_model(
    params: ModelParams,
    output_dir: str | Path,
    dem_path: str | Path | None = None,
    osm_json_path: str | Path | None = None,
    osm_json_override: dict[str, Any] | None = None,
    progress: Progress | None = None,
) -> dict[str, Any]:
    start = time.time()
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    _progress(progress, "Projecting selected area", 0.05)
    projection = make_local_projection(params.south, params.west, params.north, params.east)
    scaler = make_scaler(projection.width_m, projection.height_m, params.max_size_mm)
    footprint_m = footprint_polygon_m(params, projection.width_m, projection.height_m)
    footprint_mm = footprint_polygon_mm(footprint_m, scaler)

    terrain_message = "Loading uploaded DEM terrain" if dem_path else (
        "Downloading terrain tiles" if params.auto_terrain and params.large_map_mode else (
            "Downloading terrain elevation" if params.auto_terrain else "Creating flat terrain"
        )
    )
    _progress(progress, terrain_message, 0.15)
    terrain, terrain_source = make_terrain(dem_path, projection, scaler, params)

    _progress(progress, "Loading OpenStreetMap data", 0.28)
    if osm_json_override is not None:
        osm_json = osm_json_override
    elif osm_json_path:
        with open(osm_json_path, "r", encoding="utf-8") as f:
            osm_json = json.load(f)
    else:
        if params.large_map_mode:
            def osm_progress(message: str, value: float) -> None:
                _progress(progress, message, 0.24 + value * 0.14)

            osm_json = fetch_osm_json_tiled(
                params.south,
                params.west,
                params.north,
                params.east,
                params.osm_overpass_url,
                tile_size_km=params.osm_tile_size_km,
                progress=osm_progress,
            )
        else:
            osm_json = fetch_osm_json(params.south, params.west, params.north, params.east, params.osm_overpass_url)
        save_osm_json(osm_json, output_dir / "osm_raw.json")

    _progress(progress, "Parsing OSM features", 0.40)
    features = parse_osm_features(osm_json, projection)
    clip_m: BaseGeometry = footprint_m if footprint_m is not None else rectangle_polygon_m(projection.width_m, projection.height_m)
    features = clip_features_to_footprint(features, clip_m)
    buildings = [f for f in features if f.layer == "building"]
    road_candidates = [f for f in features if f.layer == "road"]
    selected_road_levels = set(params.road_levels)
    roads = [f for f in road_candidates if f.tags.get("highway") in selected_road_levels]
    water = [f for f in features if f.layer == "water"]
    green = [f for f in features if f.layer == "green"]
    parking = [f for f in features if f.layer == "parking"]
    airport = [f for f in features if f.layer == "airport"]
    area_infill = [f for f in features if f.layer == "area_infill"]

    water_cutouts = water_cutout_polygons_mm(water, scaler, params) if params.cut_out_water else []
    terrain_part = terrain_to_mesh(terrain, cutouts_mm=water_cutouts, footprint_mm=footprint_mm)
    parts: list[MeshPart] = [terrain_part]

    if params.include_buildings:
        _progress(progress, f"Extruding {len(buildings)} building features", 0.55)
        building_part = build_building_meshes(buildings, scaler, terrain, params)
        if not building_part.is_empty():
            parts.append(building_part)

    _progress(progress, "Building roads, water, green, parking, airport, and area infill layers", 0.70)
    parts.extend(build_surface_layer_meshes(
        roads,
        water,
        green,
        parking,
        airport,
        area_infill,
        buildings,
        scaler,
        terrain,
        params,
    ))
    parts = [p.cleaned() for p in parts if not p.cleaned().is_empty()]

    if not parts:
        raise RuntimeError("Generation produced no mesh parts.")

    _progress(progress, "Repairing mesh geometry", 0.82)
    parts, mesh_repair = repair_mesh_parts(parts, enabled=params.auto_repair_mesh)
    parts = [p.cleaned() for p in parts if not p.cleaned().is_empty()]
    if not parts:
        raise RuntimeError("Mesh repair removed all geometry.")

    _progress(progress, "Writing 3MF and GLB files", 0.88)
    base_name = safe_output_stem(params.output_name)
    path_3mf = write_3mf(parts, output_dir / f"{base_name}.3mf", title=params.project_name)
    path_glb = write_glb(parts, output_dir / f"{base_name}.glb")
    path_stl = write_stl(parts, output_dir / f"{base_name}.stl")
    attribution = attribution_text(params, terrain_source=terrain_source)
    path_attr = output_dir / "ATTRIBUTION.txt"
    path_attr.write_text(attribution, encoding="utf-8")

    summary = {
        "bbox": params.bbox_tuple,
        "projection_epsg": projection.epsg,
        "area_width_m": projection.width_m,
        "area_height_m": projection.height_m,
        "model_width_mm": scaler.width_mm,
        "model_height_mm": scaler.height_mm,
        "scale_mm_per_m": scaler.scale_mm_per_m,
        "output_name": base_name,
        "terrain": {
            "source": terrain_source,
            "grid": [terrain.nx, terrain.ny],
            "z_min_mm": float(terrain.z_mm.min()),
            "z_max_mm": float(terrain.z_mm.max()),
            "relief_mm": float(terrain.z_mm.max() - terrain.z_mm.min()),
        },
        "large_map_mode": params.large_map_mode,
        "selection_shape": params.selection_shape,
        "area_infill_mode": params.area_infill_mode,
        "road_cleaning_level": params.road_cleaning_level,
        "water_cutout": {
            "enabled": params.cut_out_water,
            "polygons": len(water_cutouts),
        },
        "osm_tile_count": osm_json.get("tile_count"),
        "osm_tile_errors": osm_json.get("tile_errors"),
        "features": {
            "buildings": len(buildings),
            "roads": len(roads),
            "road_candidates": len(road_candidates),
            "water": len(water),
            "green": len(green),
            "parking": len(parking),
            "airport": len(airport),
            "area_infill": len(area_infill),
        },
        "selected_road_levels": params.road_levels,
        "mesh_parts": [
            {"name": p.name, "vertices": int(len(p.vertices)), "triangles": int(len(p.faces))}
            for p in parts
        ],
        "mesh_repair": mesh_repair,
        "files": {
            "3mf": path_3mf.name,
            "glb": path_glb.name,
            "stl": path_stl.name,
            "attribution": path_attr.name,
        },
        "validation_3mf": validate_3mf(path_3mf),
        "seconds": round(time.time() - start, 3),
    }

    if params.chunk_export and params.chunk_rows * params.chunk_cols > 1:
        _progress(progress, f"Writing {params.chunk_rows * params.chunk_cols} chunk exports", 0.94)
        chunk_data = export_chunk_models(params, output_dir, dem_path, osm_json, scaler.scale_mm_per_m)
        if chunk_data:
            summary["chunk_export"] = chunk_data
            summary["files"]["chunks_zip"] = chunk_data["zip"]
            summary["files"]["chunks_manifest"] = chunk_data["manifest"]
    else:
        summary["chunk_export"] = {
            "enabled": False,
            "rows": params.chunk_rows,
            "cols": params.chunk_cols,
            "pieces": 0,
        }

    summary["printability"] = printability_report(params, summary)
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    _progress(progress, "Done", 1.0)
    return summary


def make_synthetic_osm_json(south: float, west: float, north: float, east: float) -> dict[str, Any]:
    def interp(lon_frac: float, lat_frac: float) -> tuple[float, float]:
        return west + (east - west) * lon_frac, south + (north - south) * lat_frac

    def way(osm_id: int, coords: list[tuple[float, float]], tags: dict[str, str]) -> dict[str, Any]:
        return {
            "type": "way",
            "id": osm_id,
            "tags": tags,
            "geometry": [{"lon": lon, "lat": lat} for lon, lat in coords],
        }

    elements: list[dict[str, Any]] = []
    # A park and a pond.
    park = [interp(0.08, 0.10), interp(0.92, 0.10), interp(0.92, 0.92), interp(0.08, 0.92), interp(0.08, 0.10)]
    pond = [interp(0.58, 0.56), interp(0.82, 0.55), interp(0.86, 0.72), interp(0.65, 0.78), interp(0.58, 0.56)]
    elements.append(way(100, park, {"leisure": "park"}))
    elements.append(way(101, pond, {"natural": "water"}))
    parking = [interp(0.10, 0.72), interp(0.30, 0.72), interp(0.30, 0.88), interp(0.10, 0.88), interp(0.10, 0.72)]
    elements.append(way(102, parking, {"amenity": "parking", "parking": "surface"}))

    # Roads.
    elements.append(way(200, [interp(0.05, 0.48), interp(0.95, 0.48)], {"highway": "residential"}))
    elements.append(way(201, [interp(0.42, 0.05), interp(0.42, 0.95)], {"highway": "secondary"}))
    elements.append(way(202, [interp(0.15, 0.22), interp(0.85, 0.84)], {"highway": "footway"}))

    # Buildings.
    oid = 300
    for i in range(4):
        for j in range(3):
            cx = 0.18 + i * 0.17
            cy = 0.22 + j * 0.18
            w = 0.055
            h = 0.07
            coords = [
                interp(cx - w, cy - h), interp(cx + w, cy - h), interp(cx + w, cy + h), interp(cx - w, cy + h), interp(cx - w, cy - h)
            ]
            elements.append(way(oid, coords, {"building": "yes", "building:levels": str(2 + (i + j) % 5)}))
            oid += 1
    return {"version": 0.6, "generator": "synthetic", "elements": elements}


def generate_sample(output_dir: str | Path) -> dict[str, Any]:
    params = ModelParams(
        south=47.6200,
        west=-122.3550,
        north=47.6260,
        east=-122.3455,
        max_size_mm=160,
        base_thickness_mm=3,
        vertical_exaggeration=1.5,
        project_name="Synthetic Sample City Model",
    )
    osm_json = make_synthetic_osm_json(params.south, params.west, params.north, params.east)
    return generate_model(params, output_dir, dem_path=None, osm_json_override=osm_json)
